baseURL = 'http://example.org/'
languageCode = 'en-us'
theme = 'graysx'
title = 'Athletics View'

## Site Settings
[params]
logo = "assets/img/logo.webp"
favicon = "assets/favicon.png"

# Other

# Startbootstrap Contact Form Token https://startbootstrap.com/solution/contact-forms
sbtoken = "TOKEN_HERE"

## Menu Items
[menu]
  [[menu.main]]
  name = "About"
  URL = "#about"
  weight = 1

  [[menu.main]]
  name = "Project"
  URL = "#projects"
  weight = 2

  [[menu.main]]
  name = "Contact"
  URL = "#signup"
  weight = 3
